db:
  # For users, we provide convenience database management
  # For orchestration calls, we would be better off using ENV I assume
  local:
    uri: duckdb:///example/dbt.duckdb
    db_schema_name: main_gregor_synthetic_tgt_data

  # Help identify target relationships for base extraction.
  # In the example below, {} will be replaced with the class name from the
  # linkml model.
  table_name_template: tgt_{}
data_model:
  # How does the application find the model? Has it already been added as a
  # dependency, or do we need to pull it from a file (possibly inside a GH
  # Repo). These options are mutially exclusive.
  #
  # Template repo has model defined as dependency, so we can just specify
  # how to import the model
  import_path: acr_harmonized_data_model.acr_harmonized_data_model

  # Template Repo has the model baked in as part of the repository. We
  # specify the path to the python file containing model files
  #as_file:
  #  model_filename: staging/acr_harmonized_data_model.py
  #
  # Template repo expects the application to pull the model down from a gh
  # repository based on branch, version tag, etc.
  #as_file:
  #  model_source: anvilproject/acr-harmonized-data-model
  #  model_filename: acr_harmonized_data_model.py
  #  source_ref: main # This can be commit hash, version or branch
  # There is a pattern that we will be expecting that must remain true for
  # all supported models. The actual class names are unimportant, but they
  # must be provided as entrypoints into the data itself.
  model_helpers:
    # This is the research study. Presumably, it will tie everything
    # together. I'm not sure how INCLUDE datasets will fit into this, but
    # I expect they would end up as simple members of the study.
    study:
      classname: Study
      # Which relationships are to be handled elsewhere. We should assume
      # all entries in the model_helpers are handled specially, but I'll
      # put this here as a placeholder.
      blacklist:
        - subject
    subject:
      classname: Subject
      blacklist:
        - study
projection:
  templates: example/templates
  curie_mappings:
    HP: http://purl.obolibrary.org/obo/hp.owl
    MONDO: http://purl.obolibrary.org/obo/mondo.owl
    MAXO: http://purl.obolibrary.org/obo/maxo.owl
    NCIT: http://purl.obolibrary.org/obo/ncit.owl
    SNOMED: http://snomed.info/sct
    SYMP: https://purl.obolibrary.org/obo/symp.owl
    LNC: https://loinc.org/
    MEDDRA: https://www.meddra.org
    MESH: https://www.nlm.nih.gov/mesh
    UCUM: http://unitsofmeasure.org
    OMIT: http://purl.obolibrary.org/obo/omit.owl
    MIM: https://omim.org/
    CDREC: http://terminology.hl7.org/NamingSystem/CDCREC
